export const projectType = [
	'New Construction',
	'Large Scale Renovation',
	'Small Scale Renovation',
	'Interior Design Only',
];
export const interiorSpaces = [
	'Foyer',
	'Kitchen',
	'Butlers Pantry',
	'Family Room',
	'Living Room',
	'Dining Room',
	'Bar',
	'Powder Room',
	'Laundry Room',
	'Mud Room',
	'Media Room',
	'Master Bedroom',
	'Master Bathroom',
	'Master Closet',
	'Secondary Bedrooms',
	'Secondary Bathrooms',
	'Secondary Closets',
	'Den',
	'Office',
	'Nursery',
	'Gym',
	'Pool House',
	'Basement',
	'Additional Spaces',
];
export const exteriorSpaces = [
	'Pool House Exterior',
	'California Room',
	'Sun Room',
	'Pool',
	'Spa',
	'Patios',
	'Additional Spaces Exterior',
];
export const designStyles = [
	'Modern',
	'Traditional',
	'Art Deco',
	'Bohemian',
	'Coastal',
	'Contemporary',
	'Farmhouse',
	'Transitional',
	'Eclectic',
	'Scandinavian',
	'Mid-Century Modern',
	'Industrial',
];
export const allFields = {
	'new-construction': '',
	'large-scale-renovation': '',
	'small-scale-renovation': '',
	'interior-design-only': '',
	foyer: '',
	kitchen: '',
	'butlers-pantry': '',
	'family-room': '',
	'living-room': '',
	'dining-room': '',
	bar: '',
	'powder-room': '',
	'laundry-room': '',
	'mud-room': '',
	'media-room': '',
	'master-bedroom': '',
	'master-bathroom': '',
	'master-closet': '',
	'secondary-bedrooms': '',
	'secondary-bathrooms': '',
	'secondary-closets': '',
	den: '',
	office: '',
	nursery: '',
	gym: '',
	'pool-house': '',
	basement: '',
	'additional-spaces': '',
	'california-room': '',
	'sun-room': '',
	pool: '',
	spa: '',
	patios: '',
	modern: '',
	traditional: '',
	'art-deco': '',
	bohemian: '',
	coastal: '',
	contemporary: '',
	farmhouse: '',
	transitional: '',
	eclectic: '',
	scandinavian: '',
	'mid-century-modern': '',
	industrial: '',
};

export const initialValues = {
	firstName: '',
	lastName: '',
	phone: '',
	address: '',
	state: '',
	zipcode: '',
	email: '',
	pSquareFootage: '',
	sSquareFootage: '',
	startDate: '',
	endDate: '',
	cBudget: '',
	idBudget: '',
	architect: '',
	contractor: '',
	...allFields,
};

export const formspreeMap = {
	firstName: 'firstName',
	lastName: 'lastName',
	phone: 'phone',
	address: 'address',
	state: 'state',
	city: 'city',
	zipcode: 'zipcode',
	email: 'email',
	pSquareFootage: 'pSquareFootage',
	sSquareFootage: 'sSquareFootage',
	startDate: 'startDate',
	endDate: 'endDate',
	cBudget: 'cBudget',
	idBudget: 'idBudget',
	architect: 'architect',
	contractor: 'contractor',
	'new-construction': 'projectType',
	'large-scale-renovation': 'projectType',
	'small-scale-renovation': 'projectType',
	'interior-design-only': 'projectType',
	foyer: 'group[interiorSpaces][foyer]',
	kitchen: 'group[interiorSpaces][kitchen]',
	'butlers-pantry': 'group[interiorSpaces][butlers-pantry]',
	'family-room': 'group[interiorSpaces][family-room]',
	'living-room': 'group[interiorSpaces][living-room]',
	'dining-room': 'group[interiorSpaces][dining-room]',
	bar: 'group[interiorSpaces][bar]',
	'powder-room': 'group[interiorSpaces][powder-room]',
	'laundry-room': 'group[interiorSpaces][laundry-room]',
	'mud-room': 'group[interiorSpaces][mud-room]',
	'media-room': 'group[interiorSpaces][media-room]',
	'master-bedroom': 'group[interiorSpaces][master-bedroom]',
	'master-bathroom': 'group[interiorSpaces][master-bathroom]',
	'master-closet': 'group[interiorSpaces][master-closet]',
	'secondary-bedrooms': 'group[interiorSpaces][secondary-bedrooms]',
	'secondary-bathrooms': 'group[interiorSpaces][secondary-bathrooms]',
	'secondary-closets': 'group[interiorSpaces][secondary-closets]',
	den: 'group[interiorSpaces][den]',
	office: 'group[interiorSpaces][office]',
	nursery: 'group[interiorSpaces][nursery]',
	gym: 'group[interiorSpaces][gym]',
	'pool-house': 'group[interiorSpaces][pool-house]',
	basement: 'group[interiorSpaces][basement]',
	'additional-spaces': 'group[interiorSpaces][additional-spaces]',
	'pool-house-exterior': 'group[exteriorSpaces][pool-house]',
	'california-room': 'group[exteriorSpaces][california-room]',
	'sun-room': 'group[exteriorSpaces][sun-room]',
	pool: 'group[exteriorSpaces][pool]',
	spa: 'group[exteriorSpaces][spa]',
	patios: 'group[exteriorSpaces][patios]',
	'additional-spaces-exterior': 'group[exteriorSpaces][additional-spaces]',
	modern: 'group[designStyle][modern]',
	traditional: 'group[designStyle][traditional]',
	'art-deco': 'group[designStyle][art-deco]',
	bohemian: 'group[designStyle][bohemian]',
	coastal: 'group[designStyle][coastal]',
	contemporary: 'group[designStyle][contemporary]',
	farmhouse: 'group[designStyle][farmhouse]',
	transitional: 'group[designStyle][transitional]',
	eclectic: 'group[designStyle][eclectic]',
	scandinavian: 'group[designStyle][scandinavian]',
	'mid-century-modern': 'group[designStyle][mid-century-modern]',
	industrial: 'group[designStyle][industrial]',
};
